import React from 'react';
import posts from '../posts';
import Header from './header.jsx';

const siteUrl = 'https://mushishi78.github.io/static-react-blog';
const description = 'A static-site blog generated by webpack and react.';

export default ({ children, path }) =>
  <html>
    <head>
      <meta charSet='utf-8' />
      <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
      <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      <meta name='description' content={ description } />
      <link rel='canonical' href={ siteUrl + path } />
      <title>{'Static React Blog' + title(path)}</title>
      <link href='/styles.css' rel='stylesheet' type='text/css' />
    </head>
    <body>
      <Header />
      { children }
      <script src='/client.js' />
    </body>
  </html>

function title(path) {
  return posts[path] ? ' | ' + posts[path].title : '';
}
